### ISSUE TITLE
Create namespace if it does not exist yet

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/hubploy#37]
Helm 3 related change

**Comment by salvis2** [comment]
This will require installing `kubectl` on the CircleCI machines. 

Do we need to put in some checks to see if a namespace already exists?

**Comment by salvis2** [comment]
Actually, your [commit](https://github.com/yuvipanda/hubploy/commit/edf788812b2441b10b8f935ae951b5f6bd5a84d5) seems to have done this. Close?

**Comment by yuvipanda** [comment]
Yep! Needed that for the tess stuff. Sorry I didn't notice this issue
