### ISSUE TITLE
Requirement of Repo2Docker Version Leads to JSONDecodeErrors

### ISSUE THREAD

**Issue by salvis2** [yuvipanda/hubploy#43]
The current version of hubploy requires `jupyter-repo2docker>=0.8`.

With the most recent version, 0.10.0, there comes an issue when trying to build / push the Docker image for your hub. Pushing the image with streaming output eventually returns more than one json object and the repo2docker code errors with JSONDecodeError.

Ariel started an issue that got figured out [here](https://github.com/jupyter/repo2docker/issues/801#issuecomment-536967854). So, in theory, using the master version of repo2docker avoids this error. However, the master version does not have a version number. It is listed as version 0+unknown. When installing the master version with

`pip install --upgrade https://github.com/jupyter/repo2docker/archive/master.zip`

I get the notice:

`hubploy 0.1.0 has requirement jupyter-repo2docker>=0.8, but you'll have jupyter-repo2docker 0+unknown which is incompatible.`

Attempting to run the `hubploy build` command complains similarly.

For now, I'm commenting out the jupyter-repo2docker requirement in setup.py of my hubploy image. I also have to go to `/hubploy-template/lib/python3.7/site-package/hubploy-0.1.0-py3.7.egg-info` and delete the repo2docker requirement out of `requires.txt`.

**Comment by yuvipanda** [comment]
Right, I guess we need to wait for a repo2docker release?

**Comment by yuvipanda** [comment]
and maybe remove the requirement until then

**Comment by yuvipanda** [comment]
Fixed now!
