### ISSUE TITLE
Running hubploy commands overwrites existing aws config file

### ISSUE THREAD

**Issue by salvis2** [yuvipanda/hubploy#44]
Currently, hubploy's `cluster_auth_aws()` function moves the credentials you supply in the .cfg files to the directory awscli expects them to be in (`~/.aws/credentials` for me on macos). It does this with the `shutil.copyfile()` method, ex. on [this line](https://github.com/yuvipanda/hubploy/blob/1767689c5277400a473b9f239a851f75051d8240/hubploy/auth.py#L198) of `auth.py`:

```
shutil.copyfile(service_key_path, os.path.join(cred_dir, 'credentials'))
```

The problem with this method is that it overwrites the file that was there if it existed (which is expected behavior for `shutil.copyfile()`). This leads to problems like:
- Not being able to connect to your cluster if you created it with credentials different from the ones you put in either .cfg file. Possible errors:
  - `Error: Unauthorized`
  - `error: You must be logged in to the server (Unauthorized)`
  - `could not get token: NoCredentialProviders: no valid providers in chain. Deprecated.`
- Losing lots of different credentials unrelated to the hubploy
  - Before running, recommend doing something like `cp ~/.aws/credentials ~/.aws/credentials-backup`
  - After running a `hubploy` command, can run `cp ~/.aws/credentials-backup ~/.aws/credentials` to restore old credentials.

Possible fixes / considerations:
- Would be nice if we can detect if the keys we are moving already exist in the credentials file and skip the copying if necessary.
- Copy both the credentials passed and the existing credentials in the `.aws/` directory so prevent deleting keys that aren't used for hubploy.

**Comment by salvis2** [comment]
Note: this behavior is also present in hubploy's `registry_auth_aws()` function. Both functions overwrite the aws credentials file. 

`hubploy build` calls `registry_auth_aws()`, which replaces the credentials with the supplied credentials in `aws-ecr-config.cfg`.

`hubploy deploy` calls `cluster_auth_aws()`, which replaces the credentials with the supplied credentials in `aws-eks-config.cfg`.

It looks like the equivalent gcloud and azure functions don't call `shutil.copyfile()`, so I don't think this is a problem for those providers.

**Comment by yuvipanda** [comment]
Way out of this is to turn the functions in `auth.py` into context managers. For example, with AWS, what you really want is:

1. Set `AWS_CONFIG_FILE` env var [https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html] to path to our credentials
2. Do our business (all of hubploy - including helm calls)
3. Cleanup by unsetting the env var, regardless of exit condition / exceptions.

Context Managers are perfect fit for this, and we should use them here.
