### ISSUE TITLE
Add --cleanup-on-fail option to default helm upgrade command?

### ISSUE THREAD

**Issue by scottyhq** [yuvipanda/hubploy#55]
In light of occasional failed deployments with hubploy for whatever reason (for example https://github.com/pangeo-data/pangeo-cloud-federation/issues/560) There might be some utility in adding the `--cleanup-on-fail` or `--atomic` flags as defaults or options?

from docs https://helm.sh/docs/helm/helm_upgrade/
```      
--cleanup-on-fail          allow deletion of new resources created in this upgrade when upgrade fails
--atomic                   if set, upgrade process rolls back changes made in case of failed upgrade. The --wait flag will be set automatically if --atomic is used
```

https://github.com/yuvipanda/hubploy/blob/edf788812b2441b10b8f935ae951b5f6bd5a84d5/hubploy/helm.py#L71-L84

**Comment by consideRatio** [comment]
Wow these options are VERY important I think, and I wish they would have defaulted to use these instead.

I'm not confident what to opt for, --cleanup-on-fail or --atomic. I think I understand `--atomic`, but what does really the `--cleanup-on-fail` option mean?

```
allow deletion of new resources created in this upgrade when upgrade fails
```

Allow deletion? It won't do anything, but it will allow something to be done? I assume it will actively cleanup, so it will actively delete _new_ resources, but it will not roll back modified but not new resources?

Perhaps `--atomic` is the most reliable option then?

**Comment by consideRatio** [comment]
The adding of the `--atomic` flag, which was news to me: https://github.com/helm/helm/pull/5143/files
The adding of the `--cleanup-on-fail` flag, which was also news to me: https://github.com/helm/helm/pull/4871

**Comment by consideRatio** [comment]
For Hubploy, i suggest replacing `--wait` with `--atomic`. `--atomic` implies wait, and is robust and sensible for `helm install` as well as `helm upgrade` and `helm ugprade --install`.
