### ISSUE TITLE
Support using roles instead of AWS use accounts

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/hubploy#70]
When authenticating to AWS services (EKS and ECR), we currently require AWS user accounts, with credentials generated and checked in. This isn't good practice - we should instead be using roles, and assuming them when needed.

In https://github.com/yuvipanda/hubploy/blob/master/hubploy/auth.py#L84, we set `AWS_SHARED_CREDENTIALS_FILE` to the path of the AWS user credentials for pushing images. This is good enough to help us do a docker pull or push.

In https://github.com/yuvipanda/hubploy/blob/master/hubploy/auth.py#L225, we do very much the same for EKS.

Instead, we should assume the appropriate role (for ECR, or EKS) for the duration of the operation, and drop those permissions afterwards. We can require the role names be passed in via hubploy.yaml - if you add an extra parameter to [this function signature](https://github.com/yuvipanda/hubploy/blob/master/hubploy/auth.py#L219), that key can now be used in hubploy.yaml. 

We should not remove current support we have for AWS user keys though, as many users depend on it.

**Comment by salvis2** [comment]
Should #82 have closed this issue?

**Comment by consideRatio** [comment]
I think so yepp! Thank you @yuvipanda @cslocum @salvis2 for idea, implementation, and attention! :heart: :tada:
