### ISSUE TITLE
Add boto3 to required modules

### ISSUE THREAD

**Issue by cslocum** [yuvipanda/hubploy#76]
One of our developers just ran into this.  I must have had boto3 already installed, and it is not included as a hubploy requirement.

**Comment by consideRatio** [comment]
@cslocum I learned from [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/index.html) that this is an AWS tool of some kind.

I figure it should not be a general requirement for hubploy as people may use hubploy with google cloud specifically or azure cloud specifically. Perhaps it should be as a requirement if you install hubploy like `pip install hubploy[aws]` or similar, but for me to work with this issue further I would need to clearly connect the issue experienced with the hubploy code base.

Can you share a specific error thrown by hubploy, and more information in general? I've not worked much with AWS and currently work with Google Cloud only so I have a hard time considering this further without additional details.

**Comment by consideRatio** [comment]
Oh! I now spotted `import boto3` in the code base and also that `boto3` was added as a requirement already.

Ah wieee you fixed it in https://github.com/yuvipanda/hubploy/pull/82 !! Nice! I'm closing this :)

**Comment by cslocum** [comment]
Sorry just seeing this!  You're right - it should not be a general requirement as it is AWS specific.  The imports can be more localized too.
