### ISSUE TITLE
Support charts that wrap z2jh

### ISSUE THREAD

**Issue by yuvipanda** [yuvipanda/hubploy#9]
Some charts - like Pangeo & binderhub - wrap around the z2jh chart, and we should support those too. Primary difference is probably around how nested the jupyterhub config is - and we should make sure this is configurable.

**Comment by jhamman** [comment]
@yuvipanda - what is the development path forward here?

**Comment by yuvipanda** [comment]
@jhamman I think the only two things that matter are the overrides for the image name and tag. Those are hardcoded in https://github.com/yuvipanda/hubploy/blob/master/hubploy/helm.py#L109 now - we should allow them to be overridden in hubploy.yaml to support arbitrary wrappings.
